---
- name: install base env
  hosts: img
  user: root
  vars:
    root_dir: /root/workshop

  tasks:
    - name: useradd user
      user: name={{item}}  shell=/bin/bash
      with_items:
        - "{{uname}}"
        
    - name: mkdir .ssh
      file: path=/home/{{item}}/.ssh state=directory
      with_items:
        - "{{uname}}"

    - name: create authorized_key
      user: name={{item}} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
      with_items:
        - "{{uname}}"
    - name: copy local user pub key to remote
      copy: src=/home/{{uname}}/.ssh/id_rsa.pub dest=/home/{{uname}}/.ssh/authorized_keys 

