---
- name: install base env
  hosts: base
  vars:
    root_dir: /root/workshop

  tasks:
    - name: update apt
      apt: update_cache=yes cache_valid_time=3600

    - name: install base software
      apt: name={{item}} state=present
      with_items:
        - sysstat
        - autoconf
        - gcc
        - make
        - git
        - tree
        - traceroute
        - openjdk-7-jdk
        - supervisor

    - name: ssh 
      file: path=/root/.ssh state=directory

    - name: copy root ssh key
      copy: dest=/root/.ssh/authorized_keys src={{root_dir}}/installation/src/ssh/pub_keys

    - name: copy vim config
      copy: dest=/etc/vim/vimrc.local src={{root_dir}}/installation/src/vim/vimrc

