---
- name: install nginx
  hosts: img
  vars:
    root_dir: /root/workshop

  tasks:
    - name: apt install dependence lib
      yum: name={{item}} state=present
      with_items:
        - gd
        - gd-devel
        - gcc-c++
        - pcre
        - pcre-devel
        - zlib
        - zlib-devel
        - openssl
        - openssl-devel

    - name: copy nginx1.8 tarball
      copy: src={{root_dir}}/install/src/nginx/nginx-1.8.1.tar.gz
            dest=/root/nginx-1.8.1.tar.gz

    - name: extract nginx1.8 tarball
      command: tar xf /root/nginx-1.8.1.tar.gz
               chdir=/root

    - name: configure nginx source code
      command: ./configure 
               --prefix=/opt/nginx1.8 
               --with-http_stub_status_module 
               --with-http_realip_module 
               --with-http_ssl_module 
               chdir=/root/nginx-1.8.1

    - name: make install nginx1.8
      shell: make && make install
             chdir=/root/nginx-1.8.1

    - name: create nginx conf.d dir
      file: path=/opt/nginx1.8/conf/conf.d
            state=directory
            owner=root group=root mode=0644

    - name: copy nginx
      copy: dest=/opt/nginx1.8/conf/nginx.conf
            src={{root_dir}}/install/src/nginx/nginx.conf

    - name: create nginx log dir
      file: path=/var/log/nginx
            state=directory
            owner=root group=root mode=0644

    - name: copy nginx logrotate conf
      copy: src={{root_dir}}/install/src/nginx/logrotate.conf
            dest=/etc/logrotate.d/nginx
            owner=root group=root mode=0644

    - name: clean up
      command: rm -rf /root/nginx-1.8.1 /root/nginx-1.8.1.tar.gz
               chdir=/root

    - name: start nginx
      command: /opt/nginx1.8/sbin/nginx

