---
- name: install base env
  hosts: img
  user: root
  vars:
    root_dir: /root/workshop

  tasks:
    - name: useradd user
      user: name={{item}} password='$1$T5Ehc$vu5X9e0t9OILroVEiqbYf1' shell=/bin/bash
      with_items:
        - hjhuang
        
    - name: mkdir .ssh
      file: path=/home/{{item}}/.ssh state=directory
      with_items:
        - hjhuang

    - name: create authorized_key
      user: name={{item}} generate_ssh_key=yes ssh_key_bits=1024 ssh_key_file=.ssh/id_rsa
      with_items:
        - hjhuang
