---
- name: op base env
  hosts: img
  user: root
  vars:
    root_dir: /root/workshop

  tasks:
  #   - name: copy op
   #    synchronize: dest=/tmp/op
    #         src={{root_dir}}/install/src/base/op

    # - name: copy pyyx.conf
     #  synchronize: dest=/opt/nginx1.8/conf/conf.d
      #       src={{root_dir}}/nginx/pyyx.conf

    # - name: copy font_ttf
    #   synchronize: dest=/tmp
    #         src={{root_dir}}/nginx/font_ttf.tar.gz
    # - name: create api website base dir 
     #  shell: mkdir -p /opt/pyyx_api/api_releases;mkdir -p /opt/pyyx_website/website_releases

     - name: copy api
       synchronize: dest=/opt/pyyx_api/api_releases src=/data/publish_release/api/{{api_version}}

     - name: link to api new version
       file: state=link force=true src=/opt/pyyx_api/api_releases/{{api_version}} dest=/opt/pyyx_api/api

     - name: copy website
       synchronize: dest=/opt/pyyx_website/website_releases src=/data/publish_release/website/{{website_version}}

     - name: link to website new version
       file: state=link force=true src=/opt/pyyx_website/website_releases/{{website_version}} dest=/opt/pyyx_website/website

     - name: copy pyyx
       synchronize: dest=/opt/pyyx/prod_releases src=/data/pyyx/{{pyyx_version}}

     - name: link to pyyx new version
       file: state=link force=true src=/opt/pyyx/prod_releases/{{pyyx_version}} dest=/opt/pyyx/prod

#     - name: copy pyyx.conf
 #      synchronize: dest=/opt/nginx1.8/conf/conf.d src={{root_dir}}/nginx/pyyx.conf

   #  - name: set eth0 mtu 
    #   shell: ifconfig eth0 mtu 1360

   #  - name: exec op script
    #   shell: /bin/sh /tmp/op /dev/vdb

