---
- name: install zabbix agent
  hosts: zabbix
  vars:
    root_dir: /root/workshop

  tasks:
    - name: yum install dependence lib
      yum: name={{item}} state=present
      with_items:
        - mysql-devel
        - libxml2-devel
        - net-snmp-devel
        - libcurl-devel

    - name: copy zabbix tarball
      copy: src={{root_dir}}/install/src/zabbix/zabbix-3.0.3.tar.gz
            dest=/root/zabbix-3.0.3.tar.gz

    - name: extract zabbix-3.0.3.tar.gz tarball
      command: tar xf /root/zabbix-3.0.3.tar.gz
               chdir=/root

    - name: configure nginx source code
      command: ./configure 
               --prefix=/usr/local/zabbix-agent
               --enable-agent
               chdir=/root/zabbix-3.0.3

    - name: make install zabbix-3.0.3
      shell: make && make install
             chdir=/root/zabbix-3.0.3

    - name: add user zabbix
      shell: useradd zabbix -s /sbin/nologin

    - name: create zabbix log file
      file: path=/var/log/zabbix
            state=directory
            owner=zabbix group=zabbix mode=0774

    - name: copy zabbix_agentd.conf
      copy: dest=/usr/local/zabbix-agent/etc/zabbix_agentd.conf
            src={{root_dir}}/install/src/zabbix/zabbix_agentd.conf

    - name: copy zabbix_agentd
      copy: dest=/etc/init.d/zabbix_agentd
            src={{root_dir}}/install/src/zabbix/zabbix_agentd

    - name: chmod zabbix_agentd
      shell: chmod +x /etc/init.d/zabbix_agentd

    - name: add server
      shell: chkconfig --level 35 zabbix_agentd on

    - name: clean up
      command: rm -rf /root/zabbix-3.0.3 /root/zabbix-3.0.3.tar.gz
               chdir=/root


